name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~

            if [ ! -d assignment-tracker-backend ]; then
              git clone https://github.com/bhoomisharma-31/assignment-tracker-backend.git
            fi

            cd assignment-tracker-backend

            git fetch origin
            git reset --hard origin/main

            python3 -m venv venv || true

            source venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt

            nohup python3 app.py > output.log 2>&1 < /dev/null &

            echo "Deployment Successful"